name: App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  prefix: 'platform'

jobs:
  IaC:
    
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Build App Environment
        id: build_env
        uses: azure/arm-deploy@v1
        with:
          deploymentName: "deploy-environment-${{ github.run_number }}"
          resourceGroupName: ${{ secrets.APPRESOURCEGROUP }}
          template: ./deployment/app.bicep
          parameters: >
            prefix=${{ env.prefix }}
            branch=${{ github.ref }}
            version=${{ github.run_number }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
